discover_trend:
  description: >
    Analyze current web trends and propose 3 relevant blog topics suitable for our social media audience.
  expected_output: >
    A list of 3 trending topics with 1-2 sentence explanations each.
  agent: trend_hunter

write_blog:
  description: >
    Based on the chosen topic, draft a full-length blog post including a catchy title, introduction, body, and conclusion.
  expected_output: >
    A complete draft blog post.
  agent: writer

edit_blog:
  description: >
    Review and refine the draft for clarity, tone, grammar, and style consistency.
  expected_output: >
    A polished final draft ready for publication.
  agent: editor

summarize_blog:
  description: >
    Generate a meta description (max 160 characters) and a short preview summary of the blog.
  expected_output: >
    A meta description and preview text.
  agent: summarizer
